spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
  datasource:
    url: jdbc:h2:mem:dividend;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show_sql: true
    defer-datasource-initialization: true

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
